-- MySQL Script generated by MySQL Workbench
-- Sat 01 Aug 2015 06:19:44 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mubsonedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mubsonedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mubsonedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mubsonedb` ;

-- -----------------------------------------------------
-- Table `mubsonedb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`User` (
  `idUser` INT NOT NULL COMMENT '',
  `Firstname` VARCHAR(45) NULL COMMENT '',
  `Lastname` VARCHAR(45) NULL COMMENT '',
  `Username` VARCHAR(45) NULL COMMENT '',
  `Password` VARCHAR(45) NULL COMMENT '',
  `Rating` INT NULL COMMENT '',
  `Fans` INT NULL COMMENT '',
  `Biography` TINYTEXT NULL COMMENT '',
  `isBanned` TINYINT(1) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Avatar` VARCHAR(45) NULL COMMENT '',
  `isAdmin` TINYINT(1) NULL COMMENT '',
  `isPremium` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idUser`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mubsonedb`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`Notification` (
  `idNotification` INT NOT NULL COMMENT '',
  `Content` TINYTEXT NULL COMMENT '',
  `User` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idNotification`, `User`)  COMMENT '',
  INDEX `fk_Notification_User_idx` (`User` ASC)  COMMENT '',
  CONSTRAINT `fk_Notification_User`
    FOREIGN KEY (`User`)
    REFERENCES `mubsonedb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mubsonedb`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`Artist` (
  `idArtist` INT NOT NULL COMMENT '',
  `Firstname` VARCHAR(45) NULL COMMENT '',
  `Lastname` VARCHAR(45) NULL COMMENT '',
  `Biography` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idArtist`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mubsonedb`.`User_has_Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`User_has_Artist` (
  `User` INT NOT NULL COMMENT '',
  `Artist` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User`, `Artist`)  COMMENT '',
  INDEX `fk_User_has_Artist_Artist1_idx` (`Artist` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_Artist_User1`
    FOREIGN KEY (`User`)
    REFERENCES `mubsonedb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Artist_Artist1`
    FOREIGN KEY (`Artist`)
    REFERENCES `mubsonedb`.`Artist` (`idArtist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mubsonedb`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`Video` (
  `idVideo` INT NOT NULL COMMENT '',
  `Title` VARCHAR(45) NULL COMMENT '',
  `Category` VARCHAR(45) NULL COMMENT '',
  `Date` DATE NULL COMMENT '',
  `Rating` INT NULL COMMENT '',
  `NumberOfRates` INT NULL COMMENT '',
  `Length` INT NULL COMMENT '',
  `NumberOfViews` INT NULL COMMENT '',
  `Description` TINYTEXT NULL COMMENT '',
  `User` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idVideo`, `User`)  COMMENT '',
  INDEX `fk_Video_User1_idx` (`User` ASC)  COMMENT '',
  CONSTRAINT `fk_Video_User1`
    FOREIGN KEY (`User`)
    REFERENCES `mubsonedb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mubsonedb`.`Follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`Follow` (
  `User` INT NOT NULL COMMENT '',
  `FollowsUser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User`, `FollowsUser`)  COMMENT '',
  INDEX `fk_Follow_2_idx` (`FollowsUser` ASC)  COMMENT '',
  CONSTRAINT `fk_Follow_User1`
    FOREIGN KEY (`User`)
    REFERENCES `mubsonedb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Follow_User2`
    FOREIGN KEY (`FollowsUser`)
    REFERENCES `mubsonedb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mubsonedb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mubsonedb`.`Article` (
  `idArticle` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Price` FLOAT NULL COMMENT '',
  `Category` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idArticle`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
